#!/bin/bash
# One-command launcher for the yolo26n-pose Squat Fitness Mini-Game
# Generated by DX Agent-Driven Dev
#
# Headless validation (default):  bash run.sh
# Live on-screen window:          DISPLAY_MODE=1 bash run.sh
# Custom video:                   VIDEO=/path/to/clip.mp4 bash run.sh

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- Auto-detect suite root (for cross-project references) ---
SUITE_ROOT="$SCRIPT_DIR"
while [ "$SUITE_ROOT" != "/" ]; do
    if [ -d "$SUITE_ROOT/dx-runtime" ] && [ -d "$SUITE_ROOT/dx-compiler" ]; then
        break
    fi
    SUITE_ROOT="$(dirname "$SUITE_ROOT")"
done
if [ "$SUITE_ROOT" = "/" ]; then
    echo "WARNING: Cannot find dx-all-suite root (expected dx-runtime/ and dx-compiler/ siblings)"
fi
RUNTIME_DIR="$SUITE_ROOT/dx-runtime"

# --- Activate venv (relocatable; do NOT re-run setup.sh here) ---
if [ -d "$SCRIPT_DIR/venv" ]; then
    source "$SCRIPT_DIR/venv/bin/activate"
elif [ -d "$SCRIPT_DIR/.venv" ]; then
    source "$SCRIPT_DIR/.venv/bin/activate"
elif [ -x "$RUNTIME_DIR/venv-dx-runtime/bin/python" ]; then
    source "$RUNTIME_DIR/venv-dx-runtime/bin/activate"
else
    echo "[WARN] no venv found — run 'bash setup.sh' first if imports fail"
fi

# --- Model resolution (CANONICAL — bundled-first, then suite assets) ---
MODEL_NAME="yolo26n-pose.dxnn"
MODEL="${DXNN_MODEL:-}"
if [ -z "$MODEL" ]; then
    for _c in "$SCRIPT_DIR/$MODEL_NAME" \
              "$RUNTIME_DIR/dx_app/assets/models/$MODEL_NAME" \
              "$RUNTIME_DIR/dx_app/assets/models"/models-*/"$MODEL_NAME"; do
        if [ -f "$_c" ]; then MODEL="$_c"; break; fi
    done
fi
if [ -z "$MODEL" ] || [ ! -f "$MODEL" ]; then
    echo "[ERROR] $MODEL_NAME not found." >&2
    echo "  searched: ./ and \$SUITE_ROOT/dx-runtime/dx_app/assets/models[/models-*]" >&2
    echo "  -> Set:      DXNN_MODEL=/path/to/$MODEL_NAME bash run.sh" >&2
    echo "  -> Or fetch: (cd \"\$SUITE_ROOT/dx-runtime/dx_app\" && ./setup.sh --models yolo26n-pose)" >&2
    exit 1
fi

# --- Input video: prefer media bundled WITH this app (sample/), else dx_app's ---
if [ -f "$SCRIPT_DIR/sample/squat_demo.mp4" ]; then
    VIDEO="${VIDEO:-$SCRIPT_DIR/sample/squat_demo.mp4}"
else
    VIDEO="${VIDEO:-$RUNTIME_DIR/dx_app/assets/videos/dance-solo.mov}"
fi
if [ ! -f "$VIDEO" ]; then
    echo "[ERROR] input video not found: $VIDEO" >&2
    exit 1
fi

echo "[INFO] Model: $MODEL"
echo "[INFO] Video: $VIDEO"

# --- Standalone PYTHONPATH (belt-and-suspenders for the dynamic walker) ---
_v3_search="$SCRIPT_DIR"
while [ "$_v3_search" != "/" ]; do
    if [ -d "$_v3_search/src/python_example/common" ]; then
        export PYTHONPATH="$_v3_search/src/python_example${PYTHONPATH:+:$PYTHONPATH}"
        break
    fi
    _v3_search="$(dirname "$_v3_search")"
done

# --- Run the squat game ---
# Default = headless validation: no window, save annotated output video.
# Set DISPLAY_MODE=1 for a live on-screen window instead.
if [ "${DISPLAY_MODE:-0}" = "1" ]; then
    DISP_ARGS="--display"
else
    DISP_ARGS="--no-display --save --save-dir $SCRIPT_DIR/output"
fi

python "$SCRIPT_DIR/yolo26n_pose_squat_sync.py" \
    --model "$MODEL" \
    --video "$VIDEO" \
    --show-log \
    $DISP_ARGS
