#!/bin/bash
# One-command launcher: export yolo26n.pt then run inference on bus.jpg
# Generated by DX Agent-Driven Dev — claude / sonnet46
set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Auto-detect suite root
SUITE_ROOT="$SCRIPT_DIR"
while [ "$SUITE_ROOT" != "/" ]; do
    if [ -d "$SUITE_ROOT/dx-runtime" ] && [ -d "$SUITE_ROOT/dx-compiler" ]; then break; fi
    SUITE_ROOT="$(dirname "$SUITE_ROOT")"
done
if [ "$SUITE_ROOT" = "/" ]; then
    echo "ERROR: Cannot find dx-all-suite root (expected dx-runtime/ and dx-compiler/ siblings)"
    exit 1
fi

VENV="$SUITE_ROOT/dx-runtime/venv-dx-runtime"
if [ -d "$VENV" ]; then
    source "$VENV/bin/activate"
else
    echo "[WARN] venv-dx-runtime not found — run setup.sh first if imports fail"
fi

echo "======================================================"
echo " YOLO26n → DeepX NPU  (Ultralytics format=deepx)"
echo "======================================================"
echo ""

# Skip export if model dir already exists (idempotent)
if [ -d "$SCRIPT_DIR/yolo26n_deepx_model" ] && [ -f "$SCRIPT_DIR/yolo26n_deepx_model/yolo26n.dxnn" ]; then
    echo "[run] yolo26n_deepx_model/ already exists — skipping export"
else
    echo "=== STEP 1: Export (format=deepx) ==="
    python "$SCRIPT_DIR/export.py"
    echo ""
fi

echo "=== STEP 2: Verify artifacts ==="
python "$SCRIPT_DIR/verify.py"
echo ""

echo "=== STEP 3: Inference on bus.jpg ==="
python "$SCRIPT_DIR/infer.py"
echo ""

echo "======================================================"
echo " ALL DONE"
echo "======================================================"
