#!/bin/bash
# Setup for YOLO26n → DeepX NPU (Ultralytics format=deepx)
# Generated by DX Agent-Driven Dev — claude / sonnet46
set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Auto-detect suite root
SUITE_ROOT="$SCRIPT_DIR"
while [ "$SUITE_ROOT" != "/" ]; do
    if [ -d "$SUITE_ROOT/dx-runtime" ] && [ -d "$SUITE_ROOT/dx-compiler" ]; then break; fi
    SUITE_ROOT="$(dirname "$SUITE_ROOT")"
done
if [ "$SUITE_ROOT" = "/" ]; then
    echo "ERROR: Cannot find dx-all-suite root (expected dx-runtime/ and dx-compiler/ siblings)"
    exit 1
fi

VENV="$SUITE_ROOT/dx-runtime/venv-dx-runtime"
if [ ! -d "$VENV" ]; then
    echo "ERROR: venv-dx-runtime not found at $VENV"
    echo "Fix: cd $SUITE_ROOT/dx-runtime && bash install.sh --all --exclude-app --exclude-stream"
    exit 1
fi

echo "[setup] Suite root: $SUITE_ROOT"
echo "[setup] Activating: $VENV"
source "$VENV/bin/activate"

python -c "import ultralytics; print('[OK] ultralytics', ultralytics.__version__)"
python -c "import dx_engine; print('[OK] dx_engine')"
python -c "import dx_com; print('[OK] dx_com', dx_com.__version__)"

echo ""
echo "[setup] All dependencies verified. Run: bash run.sh"
