"""Parse runnability_report.md into per-session scores.

The runnability report is generated by insights.py --mode runnability, where an LLM
evaluates each session's README.md/setup.sh/run.sh for end-user reproducibility.

Each entry follows the format:
    ### R<N> <tool> <scenario>
    - **end-user runnability**: PASS / PARTIAL / FAIL
    - **README clarity (1-5)**: <score>
    - **Setup completeness (1-5)**: <score>
    - **Run instructions completeness (1-5)**: <score>
    - **Verification provided (Y/N)**: Y/N

Composite runnability score (0-100):
    40% runnability verdict  (PASS=100, PARTIAL=50, FAIL=0)
    20% README clarity       (1-5 → 0-100)
    20% Setup completeness   (1-5 → 0-100)
    15% Run completeness     (1-5 → 0-100)
     5% Verification         (Y=100, N=0)
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple


@dataclass
class RunnabilityEntry:
    """Parsed runnability evaluation for one session."""
    tool: str
    scenario: str
    round_index: int
    verdict: str           # PASS / PARTIAL / FAIL
    readme_score: int      # 1-5
    setup_score: int       # 1-5
    run_score: int         # 1-5
    verification: bool     # True = Y
    composite: float       # 0-100

    @staticmethod
    def compute_composite(verdict: str, readme: int, setup: int,
                          run: int, verification: bool) -> float:
        v_map = {"PASS": 100.0, "PARTIAL": 50.0, "FAIL": 0.0}
        v_score = v_map.get(verdict.upper(), 0.0)
        readme_pct = (readme - 1) / 4.0 * 100.0 if readme >= 1 else 0.0
        setup_pct = (setup - 1) / 4.0 * 100.0 if setup >= 1 else 0.0
        run_pct = (run - 1) / 4.0 * 100.0 if run >= 1 else 0.0
        verif_pct = 100.0 if verification else 0.0
        return (0.40 * v_score + 0.20 * readme_pct + 0.20 * setup_pct
                + 0.15 * run_pct + 0.05 * verif_pct)


# Tool name normalization (runnability report may use short names)
_TOOL_ALIASES = {
    "claude-code": "claude-code",
    "claude": "claude-code",
    "copilot-cli": "copilot-cli",
    "copilot": "copilot-cli",
    "cursor-cli": "cursor-cli",
    "cursor": "cursor-cli",
    "opencode-cli": "opencode-cli",
    "opencode": "opencode-cli",
    "codex-cli": "codex-cli",
    "codex": "codex-cli",
}


def _normalize_tool(raw: str) -> str:
    return _TOOL_ALIASES.get(raw.lower().strip(), raw.lower().strip())


def parse_runnability_report(path: Path) -> List[RunnabilityEntry]:
    """Parse a runnability_report.md file into structured entries."""
    if not path.is_file():
        return []
    text = path.read_text(encoding="utf-8", errors="ignore")
    entries: List[RunnabilityEntry] = []

    # Split by ### headers
    sections = re.split(r"(?=^###\s)", text, flags=re.MULTILINE)
    for section in sections:
        section = section.strip()
        if not section.startswith("###"):
            continue

        # Parse header: ### R<N> <tool> <scenario>
        header_match = re.match(
            r"###\s+R(\d+)\s+(\S+)\s+(\S+)",
            section.split("\n")[0],
        )
        if not header_match:
            continue
        round_idx = int(header_match.group(1))
        tool = _normalize_tool(header_match.group(2))
        scenario = header_match.group(3).strip()

        # Parse fields
        verdict = _extract_field(section, r"end-user runnability.*?:\s*(PASS|PARTIAL|FAIL)", "FAIL")
        readme = _extract_int(section, r"README clarity.*?:\s*(\d)", 1)
        setup = _extract_int(section, r"Setup completeness.*?:\s*(\d)", 1)
        run = _extract_int(section, r"Run instructions completeness.*?:\s*(\d)", 1)
        verif_str = _extract_field(section, r"Verification provided.*?:\s*(Y|N|Yes|No)", "N")
        verification = verif_str.upper().startswith("Y")

        composite = RunnabilityEntry.compute_composite(
            verdict, readme, setup, run, verification,
        )
        entries.append(RunnabilityEntry(
            tool=tool, scenario=scenario, round_index=round_idx,
            verdict=verdict.upper(), readme_score=readme, setup_score=setup,
            run_score=run, verification=verification, composite=composite,
        ))

    return entries


def _extract_field(text: str, pattern: str, default: str) -> str:
    m = re.search(pattern, text, re.IGNORECASE)
    return m.group(1) if m else default


def _extract_int(text: str, pattern: str, default: int) -> int:
    m = re.search(pattern, text, re.IGNORECASE)
    if m:
        try:
            return int(m.group(1))
        except ValueError:
            pass
    return default


def aggregate_runnability(
    entries: List[RunnabilityEntry],
) -> Dict[Tuple[str, str], float]:
    """Aggregate runnability entries per (tool, scenario) → average composite score."""
    by_key: Dict[Tuple[str, str], List[float]] = {}
    for e in entries:
        key = (e.tool, e.scenario)
        by_key.setdefault(key, []).append(e.composite)
    return {k: sum(v) / len(v) for k, v in by_key.items()}
