"""P5: SDK knowledge sync — generate chatbot knowledge from the canonical `.deepx` warehouse.

The `.deepx/toolsets` docs + `docs/source` are the SDK teams' maintained truth and are
continuously updated. Rather than hand-copying (which drifts), this generator reads the *live* suite
sources and emits a section-tagged ``sdk_knowledge.md`` consumed by ``prompt_builder``, plus a hash
manifest so we regenerate only when sources change (lazy resync on startup / manual refresh).

`.deepx/memory` is intentionally NOT ingested: those are the dev agents' internal working notes
(MEMORY.md, common_pitfalls, performance_patterns, …), not customer-facing SDK reference, so they
must not leak into the shipped chatbot knowledge.

Self-contained (stdlib only); no dependency on dx_agent_dev.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
from pathlib import Path

# shared/chat/knowledge_sync.py → parents: chat, shared, dx-ai-studio, dx-all-suite(SUITE_ROOT)
_DEFAULT_SUITE_ROOT = Path(__file__).resolve().parents[3]
_OUT_NAME = "sdk_knowledge.md"
_MANIFEST_NAME = "sdk_manifest.json"
_MAX_LINES_PER_SOURCE = 160  # cap to keep injected prompt size sane

# docs/source files worth surfacing to end users (overview/FAQ/compat); agent-process docs excluded.
_DOCS_SOURCE_ALLOW = (
    "faq.md", "version_compatibility.md", "getting-started.md", "installation.md",
)
_STOP = {"the", "a", "an", "and", "or", "for", "dx", "deepx", "md", "api", "guide", "reference"}


def _iter_sdk_sources(suite_root: Path):
    """Yield (relpath, abspath) for SDK knowledge sources under the suite.

    Sources: every ``*/.deepx/toolsets/*.md`` plus a curated set of ``docs/source/*.md``.
    Excludes ``*/.deepx/memory/*.md`` (internal dev-agent notes — must not ship to the chatbot)
    and agent-process docs (agents/skills/templates, CLAUDE/AGENTS).
    """
    seen = set()
    for sub in ("toolsets",):
        for p in sorted(suite_root.glob(f"**/.deepx/{sub}/*.md")):
            rel = p.relative_to(suite_root).as_posix()
            if rel not in seen:
                seen.add(rel)
                yield rel, p
    docs = suite_root / "docs" / "source"
    for name in _DOCS_SOURCE_ALLOW:
        p = docs / name
        if p.is_file():
            rel = p.relative_to(suite_root).as_posix()
            if rel not in seen:
                seen.add(rel)
                yield rel, p


def _derive_keywords(path: Path, title: str) -> list[str]:
    """Keywords for a section tag: from filename stem + title words (deduped, stopworded)."""
    raw = re.split(r"[\s\-_./]+", path.stem.lower() + " " + title.lower())
    kws = []
    for w in raw:
        w = re.sub(r"[^a-z0-9]", "", w)
        if w and w not in _STOP and w not in kws:
            kws.append(w)
    return kws[:6] or [path.stem.lower()]


def _first_title(text: str, fallback: str) -> str:
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("#"):
            return s.lstrip("#").strip() or fallback
    return fallback


def _cap(text: str) -> str:
    lines = text.splitlines()
    if len(lines) <= _MAX_LINES_PER_SOURCE:
        return text.strip()
    return "\n".join(lines[:_MAX_LINES_PER_SOURCE]).strip() + "\n\n…(truncated; see source)"


def build_sdk_markdown(suite_root: Path) -> str:
    """Assemble a section-tagged markdown doc from all SDK sources."""
    blocks = [
        "# DEEPX SDK Knowledge (auto-generated from .deepx + docs/source)",
        "<!-- AUTO-GENERATED by knowledge_sync.py — do not hand-edit; run a resync instead. -->",
    ]
    for rel, p in _iter_sdk_sources(suite_root):
        try:
            text = p.read_text(encoding="utf-8")
        except OSError:
            continue
        title = _first_title(text, p.stem)
        kws = _derive_keywords(p, title)
        blocks.append(f"## [section:{','.join(kws)}] {title}  ({rel})\n{_cap(text)}")
    return "\n\n".join(blocks) + "\n"


def source_manifest(suite_root: Path) -> dict:
    """Map of relpath → sha256 for all SDK sources (for staleness detection)."""
    manifest = {}
    for rel, p in _iter_sdk_sources(suite_root):
        try:
            manifest[rel] = hashlib.sha256(p.read_bytes()).hexdigest()
        except OSError:
            continue
    return manifest


def _atomic_write(path: Path, text: str) -> None:
    """Write ``text`` to ``path`` atomically: write to a sibling temp file, then os.replace().

    Multiple processes may read ``path`` concurrently (module servers + launcher); a plain
    write_text() would let a reader observe a truncated/partial file mid-write. os.replace()
    is an atomic rename on POSIX (and on Windows for files on the same volume), so readers
    always see either the old, complete file or the new, complete file.
    """
    tmp = path.with_name(f".{path.name}.tmp-{os.getpid()}")
    tmp.write_text(text, encoding="utf-8")
    os.replace(tmp, path)


def generate(suite_root: Path | None = None, out_dir: Path | None = None) -> int:
    """Write sdk_knowledge.md + sdk_manifest.json. Returns the number of sources included."""
    suite_root = Path(suite_root) if suite_root else _DEFAULT_SUITE_ROOT
    out_dir = Path(out_dir) if out_dir else (Path(__file__).resolve().parent / "knowledge")
    out_dir.mkdir(parents=True, exist_ok=True)
    manifest = source_manifest(suite_root)
    _atomic_write(out_dir / _OUT_NAME, build_sdk_markdown(suite_root))
    _atomic_write(out_dir / _MANIFEST_NAME, json.dumps(manifest, indent=2, sort_keys=True))
    return len(manifest)


def needs_resync(suite_root: Path | None = None, out_dir: Path | None = None) -> bool:
    """True if sources changed since last generate (or never generated)."""
    suite_root = Path(suite_root) if suite_root else _DEFAULT_SUITE_ROOT
    out_dir = Path(out_dir) if out_dir else (Path(__file__).resolve().parent / "knowledge")
    mf = out_dir / _MANIFEST_NAME
    if not mf.is_file():
        return True
    try:
        prev = json.loads(mf.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return True
    return prev != source_manifest(suite_root)


def sync_if_stale(suite_root: Path | None = None, out_dir: Path | None = None) -> bool:
    """Regenerate only if sources changed. Returns True if a regeneration happened."""
    if needs_resync(suite_root, out_dir):
        generate(suite_root, out_dir)
        return True
    return False
